### ISSUE TITLE
Fail to compile in riscv because of cpufeatures unconditional dependency 

### ISSUE THREAD

**Issue by come-maiz** [sigp/ethereum_hashing#9]
I'm trying to build the [lighthouse](https://github.com/sigp/lighthouse) ethereum client in a risc-v unmatched board, and it fails with:

```
Compiling cpufeatures v0.2.12
error: This crate works only on `aarch64`, `loongarch64`, `x86`, and `x86-64` targets.
   --> /home/come-maiz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpufeatures-0.2.12/src/lib.rs:152:1
    |
152 | compile_error!("This crate works only on `aarch64`, `loongarch64`, `x86`, and `x86-64` targets.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I [requested cpufeatures to support riscv](https://github.com/RustCrypto/utils/issues/1087), and they suggested to open an issue here to make it's dependency conditional on the architecture:

https://github.com/RustCrypto/utils/issues/1087#issuecomment-2229772782

**Comment by michaelsproul** [comment]
Are you already acquainted with @haurog ? Maybe you could work together:

- https://github.com/sigp/ethereum_hashing/pull/8

**Comment by haurog** [comment]
I pinged @come-maiz on the Ethereum-on-arm discord. Working together to get clients run on RISC-V is exciting.

**Comment by come-maiz** [comment]
nice, let's be friends @haurog :D

**Comment by come-maiz** [comment]
Thank you @michaelsproul
